"use client";

import { useEffect, useMemo, useState } from "react";
import { getBrowserSupabase } from "@/lib/supabase/client";
import ClicksChart, { type ChartPoint } from "./ClicksChart";
import Icon from "./Icon";

type ProductRow = { id: string; name: string; image_url: string | null; click_count: number; product_code: string | null; categories: { name: string } | null };
type ClickRow = { clicked_at: string; product_id: string };
type SearchRow = { query: string; results_count: number; searched_at: string };
type ViewRow = { path: string; viewed_at: string; referrer: string | null };

export default function AnalyticsAdmin() {
  const [products,setProducts] = useState<ProductRow[]>([]); const [clicks,setClicks] = useState<ClickRow[]>([]); const [searches,setSearches] = useState<SearchRow[]>([]); const [views,setViews] = useState<ViewRow[]>([]); const [range,setRange] = useState(30); const [loading,setLoading] = useState(true); const [error,setError] = useState("");
  useEffect(() => { const supabase = getBrowserSupabase(); if (!supabase) return; void (async () => { const since = new Date(); since.setDate(since.getDate()-89); const [p,c,s,v] = await Promise.all([supabase.from("products").select("id,name,image_url,click_count,product_code,categories(name)").order("click_count",{ascending:false}),supabase.from("product_clicks").select("clicked_at,product_id").gte("clicked_at",since.toISOString()),supabase.from("search_events").select("query,results_count,searched_at").gte("searched_at",since.toISOString()),supabase.from("page_views").select("path,viewed_at,referrer").gte("viewed_at",since.toISOString())]); if (p.error) setError(p.error.message); setProducts((p.data ?? []) as unknown as ProductRow[]); setClicks((c.data ?? []) as ClickRow[]); setSearches((s.data ?? []) as SearchRow[]); setViews((v.data ?? []) as ViewRow[]); setLoading(false); })(); },[]);
  const data = useMemo(() => { const since = new Date(); since.setDate(since.getDate()-(range-1)); since.setHours(0,0,0,0); const filteredClicks = clicks.filter((x) => new Date(x.clicked_at)>=since); const filteredViews = views.filter((x) => new Date(x.viewed_at)>=since); const filteredSearches = searches.filter((x) => new Date(x.searched_at)>=since); const points: ChartPoint[] = []; for (let i=range-1;i>=0;i--) { const d=new Date(); d.setHours(0,0,0,0); d.setDate(d.getDate()-i); const key=d.toISOString().slice(0,10); points.push({date:key,clicks:filteredClicks.filter((x)=>x.clicked_at.slice(0,10)===key).length}); } const queryMap=new Map<string,{count:number,zero:number}>(); filteredSearches.forEach((x)=>{const key=x.query.toLowerCase(); const current=queryMap.get(key)||{count:0,zero:0}; current.count++; if(x.results_count===0) current.zero++; queryMap.set(key,current);}); const topQueries=[...queryMap.entries()].sort((a,b)=>b[1].count-a[1].count).slice(0,10); const sources=new Map<string,number>(); filteredViews.forEach((x)=>{let source="Direto"; try { if(x.referrer) source=new URL(x.referrer).hostname.replace("www.",""); } catch {} sources.set(source,(sources.get(source)||0)+1);}); return { filteredClicks,filteredViews,filteredSearches,points,topQueries,sources:[...sources.entries()].sort((a,b)=>b[1]-a[1]).slice(0,8) }; },[clicks,views,searches,range]);
  if (loading) return <div className="admin-loading-inline">Carregando analytics...</div>;
  return <><div className="admin-page-heading-v5"><div><span>DADOS</span><h1>Analytics</h1><p>Veja o que as pessoas acessam e o que elas tentam encontrar.</p></div><select className="range-select-v5" value={range} onChange={(e)=>setRange(Number(e.target.value))}><option value="7">7 dias</option><option value="30">30 dias</option><option value="90">90 dias</option></select></div>{error ? <div className="admin-alert-v5 error">{error}</div> : null}<div className="analytics-stats-v5"><article><Icon name="eye" /><span><small>Visualizações</small><strong>{data.filteredViews.length}</strong></span></article><article><Icon name="click" /><span><small>Cliques na Shopee</small><strong>{data.filteredClicks.length}</strong></span></article><article><Icon name="search" /><span><small>Pesquisas</small><strong>{data.filteredSearches.length}</strong></span></article><article><Icon name="filter" /><span><small>Sem resultado</small><strong>{data.filteredSearches.filter((x)=>x.results_count===0).length}</strong></span></article></div><div className="analytics-grid-v5"><section className="admin-card-v5 span-2"><div className="admin-card-head-v5"><div><small>DESEMPENHO</small><h2>Cliques por dia</h2></div></div><ClicksChart data={data.points} /></section><section className="admin-card-v5"><div className="admin-card-head-v5"><div><small>PRODUTOS</small><h2>Mais clicados</h2></div></div><div className="ranking-v5">{products.slice(0,8).map((p,i)=><div key={p.id}><b>{i+1}</b>{p.image_url?<img src={p.image_url} alt=""/>:<span/>}<div><strong>{p.name}</strong><small>{p.product_code ? `Código ${p.product_code} • ` : ""}{p.categories?.name}</small></div><em>{p.click_count}</em></div>)}</div></section><section className="admin-card-v5"><div className="admin-card-head-v5"><div><small>BUSCA</small><h2>Termos pesquisados</h2></div></div><div className="query-list-v5">{data.topQueries.map(([query,info])=><div key={query}><strong>{query}</strong><span>{info.count} busca(s)</span>{info.zero?<em>{info.zero} sem resultado</em>:<em className="ok">Encontrado</em>}</div>)}</div></section><section className="admin-card-v5"><div className="admin-card-head-v5"><div><small>ORIGEM</small><h2>De onde vieram</h2></div></div><div className="source-list-v5">{data.sources.map(([source,count])=><div key={source}><span>{source}</span><strong>{count}</strong></div>)}</div></section></div></>;
}
