"use client";

import { FormEvent, useEffect, useState } from "react";
import { getBrowserSupabase } from "@/lib/supabase/client";
import type { SiteSettings } from "@/lib/types";
import { DEFAULT_SETTINGS, parseSettings } from "@/lib/utils";
import Icon from "./Icon";

const colorFields: Array<[keyof SiteSettings, string]> = [
  ["primary_color", "Cor principal"], ["secondary_color", "Fundo suave"], ["accent_color", "Cor de apoio"], ["background_color", "Fundo do site"], ["surface_color", "Fundo dos cartões"], ["text_color", "Texto principal"], ["muted_text_color", "Texto secundário"], ["border_color", "Bordas"], ["button_text_color", "Texto dos botões"],
];

export default function AppearanceAdmin() {
  const [form, setForm] = useState<SiteSettings>(DEFAULT_SETTINGS); const [tab, setTab] = useState("theme"); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  useEffect(() => { const supabase = getBrowserSupabase(); if (!supabase) return; void supabase.from("site_settings").select("key,value").then(({ data, error: loadError }) => loadError ? setError(loadError.message) : setForm(parseSettings(data))); }, []);
  function update<K extends keyof SiteSettings>(key: K, value: SiteSettings[K]) { setForm((current) => ({ ...current, [key]: value })); }
  async function save(event: FormEvent) { event.preventDefault(); setSaving(true); setMessage(""); setError(""); const supabase = getBrowserSupabase(); if (!supabase) return; const keys: Array<keyof SiteSettings> = ["primary_color","secondary_color","accent_color","background_color","surface_color","text_color","muted_text_color","border_color","button_text_color","font_family","heading_font_family","container_width","corner_radius","card_style","header_style","sticky_header","show_header_search","show_prices","show_product_codes","show_click_count","product_columns_mobile","product_columns_desktop","button_style","product_image_ratio","section_spacing","animations_enabled","shadow_strength"]; const { error: saveError } = await supabase.from("site_settings").upsert(keys.map((key) => ({ key, value: form[key] })), { onConflict: "key" }); if (saveError) setError(saveError.message); else setMessage("Aparência atualizada."); setSaving(false); }
  return <><div className="admin-page-heading-v5"><div><span>IDENTIDADE VISUAL</span><h1>Aparência</h1><p>Defina a identidade visual do site sem editar código.</p></div><a className="admin-button-v5 secondary" href="/" target="_blank"><Icon name="eye" />Ver resultado</a></div>{error ? <div className="admin-alert-v5 error">{error}</div> : null}{message ? <div className="admin-alert-v5 success">{message}</div> : null}
  <form onSubmit={save} className="appearance-layout-v5"><aside className="settings-tabs-v5">{[["theme","Cores","palette"],["layout","Layout","layout"],["cards","Produtos","products"],["header","Cabeçalho","navigation"]].map(([key,label,icon]) => <button type="button" key={key} className={tab === key ? "active" : ""} onClick={() => setTab(key)}><Icon name={icon as any} />{label}</button>)}</aside><section className="admin-card-v5 appearance-editor-v5">
    {tab === "theme" ? <><div className="admin-card-head-v5"><div><small>TEMA</small><h2>Paleta do site</h2><p>As cores são aplicadas em todo o site.</p></div></div><div className="color-grid-v5">{colorFields.map(([key,label]) => <label key={key}><span>{label}</span><div><input type="color" value={String(form[key])} onChange={(e) => update(key, e.target.value as never)} /><input value={String(form[key])} onChange={(e) => update(key, e.target.value as never)} /></div></label>)}</div><div className="theme-presets-v5"><span>Combinações rápidas</span><button type="button" onClick={() => setForm({ ...form, primary_color: "#d96c78", secondary_color: "#f3b29f", accent_color: "#8f394d", background_color: "#f6efea", surface_color: "#fff9f5", text_color: "#2a2224", muted_text_color: "#726568", border_color: "#e8d9d3", button_text_color: "#fffaf7" })}>Galeria H&S</button><button type="button" onClick={() => setForm({ ...form, primary_color: "#c96f68", secondary_color: "#efb38d", accent_color: "#7f3e45", background_color: "#f7eee7", surface_color: "#fff9f4", text_color: "#2d2422", muted_text_color: "#766762", border_color: "#ead8cf" })}>Pêssego editorial</button><button type="button" onClick={() => setForm({ ...form, primary_color: "#7f9f8c", secondary_color: "#d7c4ad", accent_color: "#4f6f60", background_color: "#f2f1e9", surface_color: "#fffdf7", text_color: "#252b28", muted_text_color: "#66706a", border_color: "#dce2da" })}>Sálvia acolhedora</button></div></> : null}
    {tab === "layout" ? <><div className="admin-card-head-v5"><div><small>ESTRUTURA</small><h2>Espaço e tipografia</h2></div></div><div className="admin-form-grid-v5"><label><span>Fonte do texto</span><select value={form.font_family} onChange={(e) => update("font_family", e.target.value)}><option>Inter</option><option>Manrope</option><option>Nunito</option><option>System</option></select></label><label><span>Fonte dos títulos</span><select value={form.heading_font_family} onChange={(e) => update("heading_font_family", e.target.value)}><option>Inter</option><option>Manrope</option><option>Nunito</option><option>Georgia</option></select></label><label><span>Largura máxima ({form.container_width}px)</span><input type="range" min="960" max="1440" step="20" value={form.container_width} onChange={(e) => update("container_width", Number(e.target.value))} /></label><label><span>Arredondamento ({form.corner_radius}px)</span><input type="range" min="0" max="32" value={form.corner_radius} onChange={(e) => update("corner_radius", Number(e.target.value))} /></label><label><span>Colunas no celular</span><select value={form.product_columns_mobile} onChange={(e) => update("product_columns_mobile", Number(e.target.value))}><option value="1">1</option><option value="2">2</option></select></label><label><span>Colunas no computador</span><select value={form.product_columns_desktop} onChange={(e) => update("product_columns_desktop", Number(e.target.value))}><option value="3">3</option><option value="4">4</option><option value="5">5</option></select></label><label><span>Espaço entre seções ({form.section_spacing}px)</span><input type="range" min="32" max="140" step="4" value={form.section_spacing} onChange={(e)=>update("section_spacing",Number(e.target.value))}/></label><label><span>Intensidade das sombras ({form.shadow_strength}%)</span><input type="range" min="0" max="20" value={form.shadow_strength} onChange={(e)=>update("shadow_strength",Number(e.target.value))}/></label><label className="checkbox-line-v5 full"><input type="checkbox" checked={form.animations_enabled} onChange={(e)=>update("animations_enabled",e.target.checked)}/>Ativar animações e transições</label></div></> : null}
    {tab === "cards" ? <><div className="admin-card-head-v5"><div><small>CATÁLOGO</small><h2>Cartões de produto</h2></div></div><div className="admin-form-grid-v5"><label><span>Estilo do card</span><select value={form.card_style} onChange={(e) => update("card_style", e.target.value as SiteSettings["card_style"])}><option value="soft">Suave, com sombra</option><option value="outlined">Contorno limpo</option><option value="flat">Sem caixa</option></select></label><label><span>Formato da imagem</span><select value={form.product_image_ratio} onChange={(e)=>update("product_image_ratio",e.target.value as SiteSettings["product_image_ratio"])}><option value="square">Quadrada</option><option value="portrait">Vertical</option><option value="landscape">Horizontal</option></select></label><label><span>Formato dos botões</span><select value={form.button_style} onChange={(e)=>update("button_style",e.target.value as SiteSettings["button_style"])}><option value="rounded">Arredondado</option><option value="pill">Cápsula</option><option value="square">Reto</option></select></label><label className="checkbox-line-v5"><input type="checkbox" checked={form.show_prices} onChange={(e) => update("show_prices", e.target.checked)} />Mostrar preços</label><label className="checkbox-line-v5"><input type="checkbox" checked={form.show_product_codes} onChange={(e) => update("show_product_codes", e.target.checked)} />Mostrar código do produto</label><label className="checkbox-line-v5"><input type="checkbox" checked={form.show_click_count} onChange={(e) => update("show_click_count", e.target.checked)} />Mostrar quantidade de acessos</label></div></> : null}
    {tab === "header" ? <><div className="admin-card-head-v5"><div><small>NAVEGAÇÃO</small><h2>Cabeçalho</h2></div></div><div className="admin-form-grid-v5"><label><span>Estilo</span><select value={form.header_style} onChange={(e) => update("header_style", e.target.value as SiteSettings["header_style"])}><option value="compact">Compacto</option><option value="centered">Centralizado</option><option value="minimal">Minimalista</option></select></label><label className="checkbox-line-v5"><input type="checkbox" checked={form.sticky_header} onChange={(e) => update("sticky_header", e.target.checked)} />Fixar cabeçalho ao rolar</label><label className="checkbox-line-v5"><input type="checkbox" checked={form.show_header_search} onChange={(e) => update("show_header_search", e.target.checked)} />Mostrar busca no cabeçalho</label></div></> : null}

    <div className="appearance-preview-v5" style={{ background: form.background_color, color: form.text_color, borderRadius: form.corner_radius }}><small>PRÉVIA RÁPIDA</small><div style={{ background: form.surface_color, borderColor: form.border_color, borderRadius: form.corner_radius }}><span style={{ color: form.primary_color }}>CATEGORIA</span><h3>Nome do produto</h3><p style={{ color: form.muted_text_color }}>Descrição curta do achadinho.</p><button style={{ background: form.primary_color, color: form.button_text_color, borderRadius: Math.max(8, form.corner_radius - 6) }}>Ver na Shopee</button></div></div>
    <div className="form-actions-v5"><button className="admin-button-v5" disabled={saving}><Icon name="save" />{saving ? "Salvando..." : "Salvar aparência"}</button></div>
  </section></form></>;
}
