"use client";

import { FormEvent, useEffect, useState } from "react";
import { getBrowserSupabase } from "@/lib/supabase/client";
import type { SiteSettings } from "@/lib/types";
import { DEFAULT_SETTINGS, parseSettings } from "@/lib/utils";
import Icon from "./Icon";

const colorFields: Array<[keyof SiteSettings, string]> = [
  ["primary_color", "Cor principal"], ["secondary_color", "Fundo suave"], ["accent_color", "Cor de apoio"], ["background_color", "Fundo do site"], ["surface_color", "Fundo dos cartões"], ["text_color", "Texto principal"], ["muted_text_color", "Texto secundário"], ["border_color", "Bordas"], ["button_text_color", "Texto dos botões"],
];

export default function AppearanceAdmin() {
  const [form, setForm] = useState<SiteSettings>(DEFAULT_SETTINGS); const [tab, setTab] = useState("theme"); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  useEffect(() => { const supabase = getBrowserSupabase(); if (!supabase) return; void supabase.from("site_settings").select("key,value").then(({ data, error: loadError }) => loadError ? setError(loadError.message) : setForm(parseSettings(data))); }, []);
  function update<K extends keyof SiteSettings>(key: K, value: SiteSettings[K]) { setForm((current) => ({ ...current, [key]: value })); }
  async function save(event: FormEvent) { event.preventDefault(); setSaving(true); setMessage(""); setError(""); const supabase = getBrowserSupabase(); if (!supabase) return; const keys: Array<keyof SiteSettings> = ["primary_color","secondary_color","accent_color","background_color","surface_color","text_color","muted_text_color","border_color","button_text_color","font_family","heading_font_family","container_width","corner_radius","card_style","header_style","sticky_header","show_header_search","show_prices","show_product_codes","show_click_count","product_columns_mobile","product_columns_desktop","custom_css"]; const { error: saveError } = await supabase.from("site_settings").upsert(keys.map((key) => ({ key, value: form[key] })), { onConflict: "key" }); if (saveError) setError(saveError.message); else setMessage("Aparência atualizada."); setSaving(false); }
  return <><div className="admin-page-heading-v5"><div><span>IDENTIDADE VISUAL</span><h1>Aparência</h1><p>Controle cores, tipografia, largura, cartões e comportamento do cabeçalho.</p></div><a className="admin-button-v5 secondary" href="/" target="_blank"><Icon name="eye" />Ver resultado</a></div>{error ? <div className="admin-alert-v5 error">{error}</div> : null}{message ? <div className="admin-alert-v5 success">{message}</div> : null}
  <form onSubmit={save} className="appearance-layout-v5"><aside className="settings-tabs-v5">{[["theme","Cores","palette"],["layout","Layout","layout"],["cards","Produtos","products"],["header","Cabeçalho","navigation"],["advanced","Avançado","code"]].map(([key,label,icon]) => <button type="button" key={key} className={tab === key ? "active" : ""} onClick={() => setTab(key)}><Icon name={icon as any} />{label}</button>)}</aside><section className="admin-card-v5 appearance-editor-v5">
    {tab === "theme" ? <><div className="admin-card-head-v5"><div><small>TEMA</small><h2>Paleta do site</h2><p>As cores são aplicadas em todo o site.</p></div></div><div className="color-grid-v5">{colorFields.map(([key,label]) => <label key={key}><span>{label}</span><div><input type="color" value={String(form[key])} onChange={(e) => update(key, e.target.value as never)} /><input value={String(form[key])} onChange={(e) => update(key, e.target.value as never)} /></div></label>)}</div><div className="theme-presets-v5"><span>Combinações rápidas</span><button type="button" onClick={() => setForm({ ...form, primary_color: "#e87378", secondary_color: "#fff5f2", accent_color: "#f4b5b3", background_color: "#fffdfc", text_color: "#242223" })}>Rosé elegante</button><button type="button" onClick={() => setForm({ ...form, primary_color: "#d75872", secondary_color: "#fff4f6", accent_color: "#f2a8b8", background_color: "#fffafb", text_color: "#221f20" })}>Rosa editorial</button><button type="button" onClick={() => setForm({ ...form, primary_color: "#c96d5d", secondary_color: "#fff6f0", accent_color: "#e8b7a4", background_color: "#fffdf9", text_color: "#282321" })}>Terracota suave</button></div></> : null}
    {tab === "layout" ? <><div className="admin-card-head-v5"><div><small>ESTRUTURA</small><h2>Espaço e tipografia</h2></div></div><div className="admin-form-grid-v5"><label><span>Fonte do texto</span><select value={form.font_family} onChange={(e) => update("font_family", e.target.value)}><option>Inter</option><option>Manrope</option><option>Nunito</option><option>System</option></select></label><label><span>Fonte dos títulos</span><select value={form.heading_font_family} onChange={(e) => update("heading_font_family", e.target.value)}><option>Inter</option><option>Manrope</option><option>Nunito</option><option>Georgia</option></select></label><label><span>Largura máxima ({form.container_width}px)</span><input type="range" min="960" max="1440" step="20" value={form.container_width} onChange={(e) => update("container_width", Number(e.target.value))} /></label><label><span>Arredondamento ({form.corner_radius}px)</span><input type="range" min="0" max="32" value={form.corner_radius} onChange={(e) => update("corner_radius", Number(e.target.value))} /></label><label><span>Colunas no celular</span><select value={form.product_columns_mobile} onChange={(e) => update("product_columns_mobile", Number(e.target.value))}><option value="1">1</option><option value="2">2</option></select></label><label><span>Colunas no computador</span><select value={form.product_columns_desktop} onChange={(e) => update("product_columns_desktop", Number(e.target.value))}><option value="3">3</option><option value="4">4</option><option value="5">5</option></select></label></div></> : null}
    {tab === "cards" ? <><div className="admin-card-head-v5"><div><small>CATÁLOGO</small><h2>Cartões de produto</h2></div></div><div className="admin-form-grid-v5"><label><span>Estilo</span><select value={form.card_style} onChange={(e) => update("card_style", e.target.value as SiteSettings["card_style"])}><option value="soft">Suave, com sombra</option><option value="outlined">Contorno limpo</option><option value="flat">Sem caixa</option></select></label><label className="checkbox-line-v5"><input type="checkbox" checked={form.show_prices} onChange={(e) => update("show_prices", e.target.checked)} />Mostrar preços</label><label className="checkbox-line-v5"><input type="checkbox" checked={form.show_product_codes} onChange={(e) => update("show_product_codes", e.target.checked)} />Mostrar código do produto</label><label className="checkbox-line-v5"><input type="checkbox" checked={form.show_click_count} onChange={(e) => update("show_click_count", e.target.checked)} />Mostrar quantidade de acessos</label></div></> : null}
    {tab === "header" ? <><div className="admin-card-head-v5"><div><small>NAVEGAÇÃO</small><h2>Cabeçalho</h2></div></div><div className="admin-form-grid-v5"><label><span>Estilo</span><select value={form.header_style} onChange={(e) => update("header_style", e.target.value as SiteSettings["header_style"])}><option value="compact">Compacto</option><option value="centered">Centralizado</option><option value="minimal">Minimalista</option></select></label><label className="checkbox-line-v5"><input type="checkbox" checked={form.sticky_header} onChange={(e) => update("sticky_header", e.target.checked)} />Fixar cabeçalho ao rolar</label><label className="checkbox-line-v5"><input type="checkbox" checked={form.show_header_search} onChange={(e) => update("show_header_search", e.target.checked)} />Mostrar busca no cabeçalho</label></div></> : null}
    {tab === "advanced" ? <><div className="admin-card-head-v5"><div><small>AVANÇADO</small><h2>CSS personalizado</h2><p>Use somente quando souber o que está alterando.</p></div></div><label className="code-editor-v5"><textarea value={form.custom_css} onChange={(e) => update("custom_css", e.target.value)} placeholder=".site-header { ... }" rows={14} spellCheck={false} /></label></> : null}
    <div className="appearance-preview-v5" style={{ background: form.background_color, color: form.text_color, borderRadius: form.corner_radius }}><small>PRÉVIA RÁPIDA</small><div style={{ background: form.surface_color, borderColor: form.border_color, borderRadius: form.corner_radius }}><span style={{ color: form.primary_color }}>CATEGORIA</span><h3>Nome do produto</h3><p style={{ color: form.muted_text_color }}>Descrição curta do achadinho.</p><button style={{ background: form.primary_color, color: form.button_text_color, borderRadius: Math.max(8, form.corner_radius - 6) }}>Ver na Shopee</button></div></div>
    <div className="form-actions-v5"><button className="admin-button-v5" disabled={saving}><Icon name="save" />{saving ? "Salvando..." : "Salvar aparência"}</button></div>
  </section></form></>;
}
