"use client";

import { FormEvent, useEffect, useState } from "react";
import { getBrowserSupabase } from "@/lib/supabase/client";
import type { Category } from "@/lib/types";
import { slugify } from "@/lib/utils";
import { validateImageFile } from "@/lib/uploads";
import Icon from "./Icon";
import CategoryAliasesAdmin from "./CategoryAliasesAdmin";

type FormState={name:string;slug:string;icon:string;image_url:string;description:string;accent_color:string;sort_order:string;is_active:boolean};
const EMPTY:FormState={name:"",slug:"",icon:"",image_url:"",description:"",accent_color:"#e87378",sort_order:"0",is_active:true};

export default function CategoriesAdmin(){
 const [categories,setCategories]=useState<Category[]>([]);const[counts,setCounts]=useState<Record<string,number>>({});const[form,setForm]=useState<FormState>(EMPTY);const[editingId,setEditingId]=useState<string|null>(null);const[open,setOpen]=useState(false);const[saving,setSaving]=useState(false);const[error,setError]=useState("");const[message,setMessage]=useState("");const[file,setFile]=useState<File|null>(null);
 async function load(){const supabase=getBrowserSupabase();if(!supabase)return;const[c,p]=await Promise.all([supabase.from("categories").select("*").order("sort_order").order("name"),supabase.from("products").select("category_id")]);if(c.error)setError(c.error.message);setCategories((c.data??[]) as Category[]);const next:Record<string,number>={};for(const row of p.data??[])next[row.category_id]=(next[row.category_id]||0)+1;setCounts(next);}
 useEffect(()=>{void load();},[]);
 function createNew(){setEditingId(null);setForm({...EMPTY,sort_order:String(categories.length+1)});setFile(null);setOpen(true);}
 function edit(item:Category){setEditingId(item.id);setForm({name:item.name,slug:item.slug,icon:item.icon||"",image_url:item.image_url||"",description:item.description||"",accent_color:item.accent_color||"#e87378",sort_order:String(item.sort_order),is_active:item.is_active});setFile(null);setOpen(true);window.scrollTo({top:0,behavior:"smooth"});}
 async function uploadImage(slug:string){if(!file)return form.image_url.trim()||null;const supabase=getBrowserSupabase();if(!supabase)return null;const validated=await validateImageFile(file);const path=`categories/${slug}-${Date.now()}.${validated.extension}`;const result=await supabase.storage.from("site-assets").upload(path,file,{contentType:validated.contentType,upsert:false});if(result.error)throw result.error;return supabase.storage.from("site-assets").getPublicUrl(path).data.publicUrl;}
 async function save(event:FormEvent){event.preventDefault();setSaving(true);setError("");setMessage("");const supabase=getBrowserSupabase();if(!supabase){setError("Supabase não configurado.");setSaving(false);return;}try{const slug=slugify(form.slug||form.name);const image_url=await uploadImage(slug);const payload={name:form.name.trim(),slug,icon:form.icon.trim()||null,image_url,description:form.description.trim()||null,accent_color:form.accent_color,sort_order:Number(form.sort_order)||0,is_active:form.is_active};const result=editingId?await supabase.from("categories").update(payload).eq("id",editingId):await supabase.from("categories").insert(payload);if(result.error)throw result.error;setMessage(editingId?"Categoria atualizada.":"Categoria criada.");setOpen(false);await load();}catch(caught){setError(caught instanceof Error?caught.message:"Erro ao salvar.");}finally{setSaving(false);}}
 async function toggle(item:Category){const supabase=getBrowserSupabase();await supabase?.from("categories").update({is_active:!item.is_active}).eq("id",item.id);await load();}
 async function remove(item:Category){if((counts[item.id]||0)>0){setError("Mova os produtos antes de excluir esta categoria.");return;}if(!confirm(`Excluir “${item.name}”?`))return;const supabase=getBrowserSupabase();await supabase?.from("categories").delete().eq("id",item.id);await load();}
 async function restoreOfficial(){const supabase=getBrowserSupabase();if(!supabase)return;setError("");setMessage("");const{error:restoreError}=await supabase.rpc("admin_restore_main_categories");if(restoreError)setError(restoreError.message);else{setMessage("As sete categorias oficiais foram restauradas.");await load();}}
 async function move(index:number,direction:-1|1){const target=index+direction;if(target<0||target>=categories.length)return;const next=[...categories];[next[index],next[target]]=[next[target],next[index]];const normalized=next.map((item,i)=>({...item,sort_order:(i+1)*10}));setCategories(normalized);const supabase=getBrowserSupabase();if(!supabase)return;await Promise.all(normalized.map((item)=>supabase.from("categories").update({sort_order:item.sort_order}).eq("id",item.id)));setMessage("Ordem atualizada.");}
 const preview=file?URL.createObjectURL(file):form.image_url;
 return <><div className="admin-page-heading-ui"><div><span>ORGANIZAÇÃO</span><h1>Categorias</h1><p>Edite as categorias principais e os nomes alternativos usados pelo importador.</p></div><div className="product-heading-actions"><button className="admin-button-ui secondary" onClick={()=>void restoreOfficial()}><Icon name="categories"/>Restaurar oficiais</button><button className="admin-button-ui" onClick={createNew}><Icon name="plus"/>Nova categoria</button></div></div>{error?<div className="admin-alert-ui error">{error}</div>:null}{message?<div className="admin-alert-ui success">{message}</div>:null}
 {open?<section className="admin-card-ui category-editor-ui"><div className="admin-card-head-ui"><div><small>{editingId?"EDIÇÃO":"NOVA CATEGORIA"}</small><h2>{form.name||"Configurar categoria"}</h2></div><button onClick={()=>setOpen(false)}><Icon name="close"/></button></div><form onSubmit={save} className="category-editor-grid-ui"><div className="category-visual-editor-ui"><div className="category-circle-preview-ui" style={{borderColor:form.accent_color,background:form.accent_color+"18"}}>{preview?<img src={preview} alt=""/>:<span>{form.icon||"✦"}</span>}</div><strong>{form.name||"Nome"}</strong><small>Assim aparece na página inicial</small><label className="admin-button-ui secondary"><Icon name="image"/>Enviar imagem<input hidden type="file" accept="image/*" onChange={(e)=>setFile(e.target.files?.[0]||null)}/></label></div><div className="admin-form-grid-ui"><label><span>Nome</span><input value={form.name} onChange={(e)=>setForm({...form,name:e.target.value,slug:editingId?form.slug:slugify(e.target.value)})} required/></label><label><span>Emoji</span><input value={form.icon} onChange={(e)=>setForm({...form,icon:e.target.value})} placeholder="🎮"/></label><label className="full"><span>Descrição</span><textarea rows={3} value={form.description} onChange={(e)=>setForm({...form,description:e.target.value})} placeholder="Uma frase curta sobre a categoria."/></label><label><span>URL amigável</span><input value={form.slug} onChange={(e)=>setForm({...form,slug:slugify(e.target.value)})} required/></label><label><span>Ordem</span><input type="number" value={form.sort_order} onChange={(e)=>setForm({...form,sort_order:e.target.value})}/></label><label className="full"><span>URL da imagem</span><input value={form.image_url} onChange={(e)=>setForm({...form,image_url:e.target.value})} placeholder="https://..."/></label><label><span>Cor de destaque</span><div className="color-inline-ui"><input type="color" value={form.accent_color} onChange={(e)=>setForm({...form,accent_color:e.target.value})}/><input value={form.accent_color} onChange={(e)=>setForm({...form,accent_color:e.target.value})}/></div></label><label className="checkbox-line-ui"><input type="checkbox" checked={form.is_active} onChange={(e)=>setForm({...form,is_active:e.target.checked})}/>Categoria visível</label><div className="form-actions-ui full"><button type="button" className="admin-button-ui secondary" onClick={()=>setOpen(false)}>Cancelar</button><button className="admin-button-ui" disabled={saving}>{saving?"Salvando...":"Salvar categoria"}</button></div></div></form></section>:null}
 <div className="category-admin-grid-ui">{categories.map((item,index)=><article key={item.id}><div className="category-card-visual-ui" style={{background:`linear-gradient(145deg,${item.accent_color||"#e87378"}24,transparent)`}}>{item.image_url?<img src={item.image_url} alt=""/>:<span>{item.icon||"✦"}</span>}<b>{counts[item.id]||0}</b></div><div><div><strong>{item.name}</strong><span className={item.is_active?"on":"off"}>{item.is_active?"Visível":"Oculta"}</span></div><p>{item.description||"Sem descrição"}</p><small>/{item.slug}</small></div><div className="category-card-actions-ui"><button onClick={()=>void move(index,-1)} disabled={index===0}><Icon name="up"/></button><button onClick={()=>void move(index,1)} disabled={index===categories.length-1}><Icon name="down"/></button><button onClick={()=>edit(item)}><Icon name="edit"/></button><button onClick={()=>void toggle(item)}><Icon name="eye"/></button><button className="danger" onClick={()=>void remove(item)}><Icon name="trash"/></button></div></article>)}</div>{!categories.length?<div className="empty-ui"><Icon name="categories" size={34}/><h3>Nenhuma categoria</h3></div>:null}<CategoryAliasesAdmin key={categories.map((category)=>category.id).join("-")} categories={categories}/></>;
}
