"use client";

import { FormEvent, useEffect, useState } from "react";
import { getBrowserSupabase } from "@/lib/supabase/client";
import type { NavigationItem } from "@/lib/types";
import Icon, { type IconName } from "./Icon";

const EMPTY = { label: "", url: "", location: "header" as NavigationItem["location"], icon: "link", sort_order: 0, is_active: true, open_new_tab: false };
export default function NavigationAdmin() {
  const [items, setItems] = useState<NavigationItem[]>([]); const [form, setForm] = useState(EMPTY); const [editingId, setEditingId] = useState<string | null>(null); const [open, setOpen] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  async function load() { const supabase = getBrowserSupabase(); if (!supabase) return; const { data, error: loadError } = await supabase.from("navigation_items").select("*").order("location").order("sort_order"); if (loadError) setError(loadError.message); else setItems((data ?? []) as NavigationItem[]); }
  useEffect(() => { void load(); }, []);
  function edit(item: NavigationItem) { setEditingId(item.id); setForm({ label: item.label, url: item.url, location: item.location, icon: item.icon || "link", sort_order: item.sort_order, is_active: item.is_active, open_new_tab: item.open_new_tab }); setOpen(true); }
  async function save(e: FormEvent) { e.preventDefault(); const supabase = getBrowserSupabase(); if (!supabase) return; const result = editingId ? await supabase.from("navigation_items").update(form).eq("id", editingId) : await supabase.from("navigation_items").insert(form); if (result.error) setError(result.error.message); else { setMessage("Menu atualizado."); setOpen(false); setEditingId(null); setForm(EMPTY); await load(); } }
  async function remove(id: string) { if (!confirm("Excluir este link?")) return; const supabase = getBrowserSupabase(); await supabase?.from("navigation_items").delete().eq("id", id); await load(); }
  const locations = [["header","Cabeçalho"],["mobile","Menu mobile"],["footer","Rodapé"]] as const;
  return <><div className="admin-page-heading-v5"><div><span>NAVEGAÇÃO</span><h1>Menus e links</h1><p>Escolha exatamente quais links aparecem em cada parte do site.</p></div><button className="admin-button-v5" onClick={() => { setForm({ ...EMPTY, sort_order: items.length + 1 }); setEditingId(null); setOpen(true); }}><Icon name="plus" />Novo link</button></div>{error ? <div className="admin-alert-v5 error">{error}</div> : null}{message ? <div className="admin-alert-v5 success">{message}</div> : null}
  {open ? <section className="admin-card-v5"><div className="admin-card-head-v5"><div><small>{editingId ? "EDIÇÃO" : "NOVO LINK"}</small><h2>Configurar link</h2></div><button onClick={() => setOpen(false)}><Icon name="close" /></button></div><form className="admin-form-grid-v5" onSubmit={save}><label><span>Texto</span><input value={form.label} onChange={(e) => setForm({ ...form, label: e.target.value })} required /></label><label><span>Destino</span><input value={form.url} onChange={(e) => setForm({ ...form, url: e.target.value })} placeholder="/#produtos ou https://..." required /></label><label><span>Local</span><select value={form.location} onChange={(e) => setForm({ ...form, location: e.target.value as NavigationItem["location"] })}><option value="header">Cabeçalho</option><option value="mobile">Menu mobile</option><option value="footer">Rodapé</option></select></label><label><span>Ícone</span><select value={form.icon} onChange={(e) => setForm({ ...form, icon: e.target.value })}><option value="home">Início</option><option value="sparkles">Destaque</option><option value="products">Produtos</option><option value="categories">Categorias</option><option value="tag">Etiqueta</option><option value="link">Link</option><option value="instagram">Instagram</option><option value="tiktok">TikTok</option></select></label><label><span>Ordem</span><input type="number" value={form.sort_order} onChange={(e) => setForm({ ...form, sort_order: Number(e.target.value) })} /></label><label className="checkbox-line-v5"><input type="checkbox" checked={form.open_new_tab} onChange={(e) => setForm({ ...form, open_new_tab: e.target.checked })} />Abrir em nova aba</label><label className="checkbox-line-v5 full"><input type="checkbox" checked={form.is_active} onChange={(e) => setForm({ ...form, is_active: e.target.checked })} />Link visível</label><div className="form-actions-v5 full"><button type="button" className="admin-button-v5 secondary" onClick={() => setOpen(false)}>Cancelar</button><button className="admin-button-v5">Salvar link</button></div></form></section> : null}
  <div className="navigation-columns-v5">{locations.map(([location,label]) => <section className="admin-card-v5" key={location}><div className="admin-card-head-v5"><div><small>LOCAL</small><h2>{label}</h2></div><span>{items.filter((i) => i.location === location).length}</span></div><div className="navigation-list-v5">{items.filter((item) => item.location === location).map((item) => <div key={item.id}><span><Icon name={(item.icon || "link") as IconName} /></span><div><strong>{item.label}</strong><small>{item.url}</small></div><b className={item.is_active ? "on" : "off"}>{item.is_active ? "Visível" : "Oculto"}</b><button onClick={() => edit(item)}><Icon name="edit" /></button><button onClick={() => void remove(item.id)}><Icon name="trash" /></button></div>)}</div></section>)}</div></>;
}
