"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { getBrowserSupabase } from "@/lib/supabase/client";
import type { Category, Product, ProductImage } from "@/lib/types";
import { formatPrice, slugify } from "@/lib/utils";
import Icon from "./Icon";

type EditorTab = "basic" | "media" | "display" | "seo";
type ProductForm = {
  name: string; slug: string; product_code: string; category_id: string; affiliate_url: string; image_url: string;
  current_price: string; old_price: string; short_description: string; tags: string; badge: string;
  is_video_product: boolean; is_pinned: boolean; video_url: string; video_posted_at: string; sort_order: string;
  seo_title: string; seo_description: string; is_active: boolean;
};
const EMPTY: ProductForm = { name:"",slug:"",product_code:"",category_id:"",affiliate_url:"",image_url:"",current_price:"",old_price:"",short_description:"",tags:"",badge:"",is_video_product:false,is_pinned:false,video_url:"",video_posted_at:"",sort_order:"0",seo_title:"",seo_description:"",is_active:true };

export default function ProductsAdmin() {
  const [products,setProducts] = useState<Product[]>([]); const [categories,setCategories] = useState<Category[]>([]); const [form,setForm] = useState<ProductForm>(EMPTY); const [editingId,setEditingId] = useState<string|null>(null); const [showForm,setShowForm] = useState(false); const [tab,setTab] = useState<EditorTab>("basic"); const [search,setSearch] = useState(""); const [status,setStatus] = useState("all"); const [categoryFilter,setCategoryFilter] = useState("all"); const [saving,setSaving] = useState(false); const [message,setMessage] = useState(""); const [error,setError] = useState(""); const [coverFile,setCoverFile] = useState<File|null>(null); const [galleryFiles,setGalleryFiles] = useState<File[]>([]); const [gallery,setGallery] = useState<ProductImage[]>([]);

  async function load() { const supabase=getBrowserSupabase(); if(!supabase)return; const [p,c]=await Promise.all([supabase.from("products").select("*,categories(id,name,slug),product_images(*)").order("is_pinned",{ascending:false}).order("created_at",{ascending:false}),supabase.from("categories").select("*").order("sort_order").order("name")]); if(p.error||c.error)setError("Não foi possível carregar o catálogo."); setProducts((p.data??[]) as Product[]); setCategories((c.data??[]) as Category[]); }
  useEffect(()=>{void load();},[]);

  const visible=useMemo(()=>products.filter((item)=>{ const text=search.toLowerCase(); const matchText=item.name.toLowerCase().includes(text)||(item.product_code||"").toLowerCase().includes(text)||(item.categories?.name||"").toLowerCase().includes(text); const matchStatus=status==="all"||(status==="active"&&item.is_active)||(status==="inactive"&&!item.is_active)||(status==="video"&&item.is_video_product)||(status==="pinned"&&item.is_pinned); const matchCategory=categoryFilter==="all"||item.category_id===categoryFilter; return matchText&&matchStatus&&matchCategory;}),[products,search,status,categoryFilter]);
  function update<K extends keyof ProductForm>(key:K,value:ProductForm[K]){setForm((current)=>({...current,[key]:value}));}
  function resetFiles(){setCoverFile(null);setGalleryFiles([]);setGallery([]);}
  function openNew(){setEditingId(null);setForm({...EMPTY,category_id:categories[0]?.id||"",sort_order:String(products.length+1)});resetFiles();setTab("basic");setShowForm(true);setError("");setMessage("");window.scrollTo({top:0,behavior:"smooth"});}
  function edit(product:Product){setEditingId(product.id);setForm({name:product.name,slug:product.slug,product_code:product.product_code||"",category_id:product.category_id,affiliate_url:product.affiliate_url,image_url:product.image_url||"",current_price:product.current_price?.toString()||"",old_price:product.old_price?.toString()||"",short_description:product.short_description||"",tags:(product.tags||[]).join(", "),badge:product.badge||"",is_video_product:Boolean(product.is_video_product||product.is_featured),is_pinned:Boolean(product.is_pinned),video_url:product.video_url||"",video_posted_at:product.video_posted_at?.slice(0,16)||"",sort_order:String(product.sort_order||0),seo_title:product.seo_title||"",seo_description:product.seo_description||"",is_active:product.is_active});setCoverFile(null);setGalleryFiles([]);setGallery([...(product.product_images||[])].sort((a,b)=>a.sort_order-b.sort_order));setTab("basic");setShowForm(true);window.scrollTo({top:0,behavior:"smooth"});}
  async function uploadOne(file:File,path:string){if(file.size>8*1024*1024)throw new Error(`A imagem “${file.name}” passa de 8 MB.`);if(!file.type.startsWith("image/"))throw new Error("Escolha uma imagem válida.");const supabase=getBrowserSupabase();if(!supabase)throw new Error("Supabase não configurado.");const result=await supabase.storage.from("product-images").upload(path,file,{contentType:file.type});if(result.error)throw result.error;return supabase.storage.from("product-images").getPublicUrl(path).data.publicUrl;}

  async function save(event:FormEvent){event.preventDefault();setSaving(true);setError("");setMessage("");const supabase=getBrowserSupabase();if(!supabase){setSaving(false);return;}try{const slug=slugify(form.slug||form.name);if(!slug)throw new Error("Informe um nome válido.");const affiliate=new URL(form.affiliate_url);if(affiliate.protocol!=="https:")throw new Error("O link precisa começar com https://");let coverUrl=form.image_url.trim()||null;if(coverFile){const ext=coverFile.name.split(".").pop()||"jpg";coverUrl=await uploadOne(coverFile,`covers/${slug}-${Date.now()}.${ext}`);}const payload={name:form.name.trim(),slug,product_code:form.product_code.trim()||null,category_id:form.category_id,affiliate_url:affiliate.toString(),image_url:coverUrl,current_price:form.current_price?Number(form.current_price.replace(",",".")):null,old_price:form.old_price?Number(form.old_price.replace(",",".")):null,short_description:form.short_description.trim()||null,tags:form.tags.split(",").map((x)=>x.trim()).filter(Boolean),badge:form.badge.trim()||null,is_featured:form.is_video_product,is_video_product:form.is_video_product,is_pinned:form.is_pinned,video_url:form.video_url.trim()||null,video_posted_at:form.video_posted_at||null,sort_order:Number(form.sort_order)||0,seo_title:form.seo_title.trim()||null,seo_description:form.seo_description.trim()||null,is_active:form.is_active};const result=editingId?await supabase.from("products").update(payload).eq("id",editingId).select("id").single():await supabase.from("products").insert(payload).select("id").single();if(result.error)throw result.error;const productId=result.data.id as string;if(coverUrl){await supabase.from("product_images").update({is_cover:false}).eq("product_id",productId);const existing=gallery.find((x)=>x.image_url===coverUrl);if(existing)await supabase.from("product_images").update({is_cover:true,sort_order:0}).eq("id",existing.id);else await supabase.from("product_images").insert({product_id:productId,image_url:coverUrl,sort_order:0,is_cover:true});}if(galleryFiles.length){const base=Math.max(1,...gallery.map((x)=>x.sort_order+1));const rows=[];for(let i=0;i<galleryFiles.length;i++){const file=galleryFiles[i];const ext=file.name.split(".").pop()||"jpg";const url=await uploadOne(file,`gallery/${productId}/${Date.now()}-${i}.${ext}`);rows.push({product_id:productId,image_url:url,sort_order:base+i,is_cover:false});}const galleryResult=await supabase.from("product_images").insert(rows);if(galleryResult.error)throw galleryResult.error;}setMessage(editingId?"Produto atualizado.":"Produto cadastrado.");setShowForm(false);setEditingId(null);setForm(EMPTY);resetFiles();await load();}catch(caught){setError(caught instanceof Error?caught.message:"Erro ao salvar produto.");}finally{setSaving(false);}}
  async function makeCover(image:ProductImage){if(!editingId)return;const supabase=getBrowserSupabase();if(!supabase)return;await supabase.from("product_images").update({is_cover:false}).eq("product_id",editingId);const [a,b]=await Promise.all([supabase.from("product_images").update({is_cover:true,sort_order:0}).eq("id",image.id),supabase.from("products").update({image_url:image.image_url}).eq("id",editingId)]);if(a.error||b.error)setError(a.error?.message||b.error?.message||"Erro.");else{update("image_url",image.image_url);setGallery((current)=>current.map((x)=>({...x,is_cover:x.id===image.id})));setMessage("Capa atualizada.");}}
  async function removeGallery(image:ProductImage){if(!confirm("Remover esta imagem?"))return;const supabase=getBrowserSupabase();const {error:removeError}=await supabase!.from("product_images").delete().eq("id",image.id);if(removeError)setError(removeError.message);else setGallery((current)=>current.filter((x)=>x.id!==image.id));}
  async function toggle(product:Product,field:"is_active"|"is_pinned"|"is_video_product"){const supabase=getBrowserSupabase();if(!supabase)return;const next=!Boolean(product[field]);const payload=field==="is_video_product"?{is_video_product:next,is_featured:next}:{[field]:next};const {error:toggleError}=await supabase.from("products").update(payload).eq("id",product.id);if(toggleError)setError(toggleError.message);else await load();}
  async function duplicate(product:Product){const supabase=getBrowserSupabase();if(!supabase)return;const copy={category_id:product.category_id,name:`${product.name} (cópia)`,slug:`${product.slug}-copia-${Date.now().toString().slice(-5)}`,product_code:null,affiliate_url:product.affiliate_url,image_url:product.image_url,current_price:product.current_price,old_price:product.old_price,short_description:product.short_description,tags:product.tags,badge:product.badge,is_featured:false,is_video_product:false,is_pinned:false,is_active:false};const {error:copyError}=await supabase.from("products").insert(copy);if(copyError)setError(copyError.message);else{setMessage("Cópia criada como rascunho.");await load();}}
  async function remove(product:Product){if(!confirm(`Excluir “${product.name}”?`))return;const supabase=getBrowserSupabase();const {error:deleteError}=await supabase!.from("products").delete().eq("id",product.id);if(deleteError)setError(deleteError.message);else{setMessage("Produto excluído.");await load();}}

  const coverPreview=coverFile?URL.createObjectURL(coverFile):form.image_url;
  const tabs:Array<[EditorTab,string,"products"|"image"|"eye"|"search"]>=[["basic","Informações","products"],["media","Imagens","image"],["display","Publicação","eye"],["seo","SEO","search"]];
  return <>
    <div className="admin-page-heading-v5"><div><span>CATÁLOGO</span><h1>Produtos</h1><p>Cadastre, prepare rascunhos e escolha o que aparece primeiro para quem veio dos vídeos.</p></div><button className="admin-button-v5" onClick={openNew}><Icon name="plus"/>Novo produto</button></div>
    {error?<div className="admin-alert-v5 error">{error}</div>:null}{message?<div className="admin-alert-v5 success">{message}</div>:null}
    <div className="catalog-stats-v5"><article><strong>{products.length}</strong><span>Total</span></article><article><strong>{products.filter((x)=>x.is_active).length}</strong><span>Publicados</span></article><article><strong>{products.filter((x)=>x.is_video_product).length}</strong><span>Dos vídeos</span></article><article><strong>{products.reduce((sum,x)=>sum+Number(x.click_count||0),0)}</strong><span>Cliques</span></article></div>

    {showForm?<section className="product-editor-v5"><div className="product-editor-top-v5"><div><small>{editingId?"EDITANDO PRODUTO":"NOVO PRODUTO"}</small><h2>{form.name||"Produto sem nome"}</h2></div><div><a href={editingId?`/produto/${form.slug}`:"#"} target="_blank" className={!editingId?"disabled":""}><Icon name="eye"/>Prévia</a><button onClick={()=>setShowForm(false)}><Icon name="close"/></button></div></div><form onSubmit={save}><nav className="product-editor-tabs-v5">{tabs.map(([key,label,icon])=><button type="button" className={tab===key?"active":""} onClick={()=>setTab(key)} key={key}><Icon name={icon}/>{label}</button>)}</nav><div className="product-editor-body-v5">
      {tab==="basic"?<div className="admin-form-grid-v5"><label className="full"><span>Nome do produto</span><input value={form.name} onChange={(e)=>{update("name",e.target.value);if(!editingId)update("slug",slugify(e.target.value));}} required placeholder="Ex.: Organizador giratório"/></label><label><span>Código para o vídeo</span><input value={form.product_code} onChange={(e)=>update("product_code",e.target.value.toUpperCase())} placeholder="Ex.: A142"/><small>Você pode falar: “procure pelo código A142”.</small></label><label><span>Categoria</span><select value={form.category_id} onChange={(e)=>update("category_id",e.target.value)} required><option value="">Selecione</option>{categories.map((c)=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label className="full"><span>Link de afiliado</span><input type="url" value={form.affiliate_url} onChange={(e)=>update("affiliate_url",e.target.value)} required placeholder="https://s.shopee.com.br/..."/></label><label><span>Preço atual</span><input inputMode="decimal" value={form.current_price} onChange={(e)=>update("current_price",e.target.value)} placeholder="39,90"/></label><label><span>Preço anterior</span><input inputMode="decimal" value={form.old_price} onChange={(e)=>update("old_price",e.target.value)} placeholder="59,90"/></label><label><span>Selo</span><input value={form.badge} onChange={(e)=>update("badge",e.target.value)} placeholder="Oferta, Novo..."/></label><label><span>Tags</span><input value={form.tags} onChange={(e)=>update("tags",e.target.value)} placeholder="cozinha, organização"/></label><label className="full"><span>Descrição curta</span><textarea rows={5} value={form.short_description} onChange={(e)=>update("short_description",e.target.value)} placeholder="Explique o produto de forma direta e natural."/></label></div>:null}
      {tab==="media"?<div className="media-editor-v5"><div className="cover-editor-v5"><div className="cover-preview-v5">{coverPreview?<img src={coverPreview} alt=""/>:<span><Icon name="image" size={34}/>Sem capa</span>}</div><div><h3>Imagem principal</h3><p>Use uma imagem quadrada, limpa e com o produto bem visível.</p><label className="admin-button-v5 secondary"><Icon name="image"/>Escolher imagem<input type="file" accept="image/*" hidden onChange={(e)=>setCoverFile(e.target.files?.[0]||null)}/></label><label><span>Ou cole a URL</span><input type="url" value={form.image_url} onChange={(e)=>update("image_url",e.target.value)}/></label></div></div><div className="gallery-editor-v5"><div><h3>Galeria</h3><p>Adicione outras fotos e escolha a capa.</p><label className="admin-button-v5"><Icon name="plus"/>Adicionar fotos<input type="file" accept="image/*" multiple hidden onChange={(e)=>setGalleryFiles(Array.from(e.target.files||[]))}/></label>{galleryFiles.length?<small>{galleryFiles.length} foto(s) pronta(s) para enviar.</small>:null}</div><div className="gallery-grid-v5">{gallery.map((image)=><article key={image.id}><img src={image.image_url} alt=""/>{image.is_cover?<b>Capa</b>:<button type="button" onClick={()=>void makeCover(image)}>Usar como capa</button>}<button type="button" className="danger" onClick={()=>void removeGallery(image)}><Icon name="trash"/></button></article>)}</div></div></div>:null}
      {tab==="display"?<div className="admin-form-grid-v5"><label className="checkbox-card-v5 full"><input type="checkbox" checked={form.is_active} onChange={(e)=>update("is_active",e.target.checked)}/><span><strong>Publicado</strong><small>O produto fica visível no site.</small></span></label><label className="checkbox-card-v5 full"><input type="checkbox" checked={form.is_video_product} onChange={(e)=>update("is_video_product",e.target.checked)}/><span><strong>Produto de vídeo</strong><small>Aparece na seção principal para quem veio da bio.</small></span></label><label className="checkbox-card-v5 full"><input type="checkbox" checked={form.is_pinned} onChange={(e)=>update("is_pinned",e.target.checked)}/><span><strong>Fixar no topo</strong><small>Fica antes dos demais produtos da mesma seção.</small></span></label><label><span>Data do vídeo</span><input type="datetime-local" value={form.video_posted_at} onChange={(e)=>update("video_posted_at",e.target.value)}/></label><label><span>Ordem manual</span><input type="number" value={form.sort_order} onChange={(e)=>update("sort_order",e.target.value)}/></label><label className="full"><span>Link do vídeo (opcional)</span><input type="url" value={form.video_url} onChange={(e)=>update("video_url",e.target.value)} placeholder="TikTok, Instagram ou YouTube"/></label><label className="full"><span>URL amigável</span><input value={form.slug} onChange={(e)=>update("slug",slugify(e.target.value))}/></label></div>:null}
      {tab==="seo"?<div className="admin-form-grid-v5"><label className="full"><span>Título no Google</span><input value={form.seo_title} onChange={(e)=>update("seo_title",e.target.value)} placeholder={form.name||"Título do produto"}/><small>{form.seo_title.length}/60 caracteres</small></label><label className="full"><span>Descrição no Google</span><textarea rows={5} value={form.seo_description} onChange={(e)=>update("seo_description",e.target.value)} placeholder={form.short_description||"Descrição curta do produto"}/><small>{form.seo_description.length}/160 caracteres</small></label><div className="seo-preview-v5 full"><small>PRÉVIA</small><h3>{form.seo_title||form.name||"Nome do produto"}</h3><span>hs-achadinhos.vercel.app/produto/{form.slug||"produto"}</span><p>{form.seo_description||form.short_description||"A descrição do produto aparecerá aqui."}</p></div></div>:null}
    </div><div className="product-editor-footer-v5"><button type="button" className="admin-button-v5 secondary" onClick={()=>setShowForm(false)}>Cancelar</button><button className="admin-button-v5" disabled={saving}><Icon name="save"/>{saving?"Salvando...":"Salvar produto"}</button></div></form></section>:null}

    <section className="admin-card-v5 catalog-list-card-v5"><div className="catalog-toolbar-v5"><div><Icon name="search"/><input placeholder="Buscar por nome, código ou categoria" value={search} onChange={(e)=>setSearch(e.target.value)}/></div><select value={status} onChange={(e)=>setStatus(e.target.value)}><option value="all">Todos os status</option><option value="active">Publicados</option><option value="inactive">Rascunhos</option><option value="video">Produtos de vídeo</option><option value="pinned">Fixados</option></select><select value={categoryFilter} onChange={(e)=>setCategoryFilter(e.target.value)}><option value="all">Todas as categorias</option>{categories.map((c)=><option value={c.id} key={c.id}>{c.name}</option>)}</select><b>{visible.length}</b></div><div className="product-table-v5"><div className="product-table-head-v5"><span>Produto</span><span>Categoria</span><span>Preço</span><span>Cliques</span><span>Status</span><span>Ações</span></div>{visible.map((product)=><article key={product.id}><div className="product-cell-v5">{product.image_url?<img src={product.image_url} alt=""/>:<span><Icon name="image"/></span>}<div><strong>{product.name}</strong><small>{product.product_code?`Código ${product.product_code}`:"Sem código"}</small></div></div><span>{product.categories?.name||"Sem categoria"}</span><strong>{formatPrice(product.current_price)||"—"}</strong><span>{product.click_count}</span><div className="status-stack-v5"><b className={product.is_active?"published":"draft"}>{product.is_active?"Publicado":"Rascunho"}</b>{product.is_video_product?<small>Do vídeo</small>:null}{product.is_pinned?<small>Fixado</small>:null}</div><div className="table-actions-v5"><button title="Editar" onClick={()=>edit(product)}><Icon name="edit"/></button><button title="Duplicar" onClick={()=>void duplicate(product)}><Icon name="copy"/></button><button title={product.is_pinned?"Desafixar":"Fixar"} onClick={()=>void toggle(product,"is_pinned")}><Icon name="up"/></button><button title="Excluir" className="danger" onClick={()=>void remove(product)}><Icon name="trash"/></button></div></article>)}</div>{!visible.length?<div className="empty-v5"><Icon name="products" size={34}/><h3>Nenhum produto encontrado</h3></div>:null}</section>
  </>;
}
