"use client";

import { FormEvent,useEffect,useState } from "react";
import { getBrowserSupabase } from "@/lib/supabase/client";
import { validateImageFile } from "@/lib/uploads";
import type { SiteSettings } from "@/lib/types";
import { DEFAULT_SETTINGS,parseSettings } from "@/lib/utils";
import Icon,{type IconName} from "./Icon";

type UploadField="logo_url"|"favicon_url"|"hero_image_url"|"og_image_url";type Tab="brand"|"content"|"social"|"seo";
export default function SettingsAdmin(){const[form,setForm]=useState<SiteSettings>(DEFAULT_SETTINGS);const[tab,setTab]=useState<Tab>("brand");const[saving,setSaving]=useState(false);const[uploading,setUploading]=useState<UploadField|null>(null);const[message,setMessage]=useState("");const[error,setError]=useState("");
 useEffect(()=>{const supabase=getBrowserSupabase();if(!supabase)return;void supabase.from("site_settings").select("key,value").then(({data,error:loadError})=>loadError?setError(loadError.message):setForm(parseSettings(data)));},[]);
 function update<K extends keyof SiteSettings>(key:K,value:SiteSettings[K]){setForm((current)=>({...current,[key]:value}));}
 async function upload(field:UploadField,file?:File){if(!file)return;setUploading(field);setError("");const supabase=getBrowserSupabase();if(!supabase)return;try{const validated=await validateImageFile(file);const path=`branding/${field}-${Date.now()}.${validated.extension}`;const result=await supabase.storage.from("site-assets").upload(path,file,{contentType:validated.contentType,upsert:false});if(result.error)throw result.error;update(field,supabase.storage.from("site-assets").getPublicUrl(path).data.publicUrl);setMessage("Imagem enviada. Salve para publicar.");}catch(caught){setError(caught instanceof Error?caught.message:"Erro no upload.");}finally{setUploading(null);}}
 async function save(event:FormEvent){event.preventDefault();setSaving(true);setError("");setMessage("");const supabase=getBrowserSupabase();if(!supabase)return;const keys:Array<keyof SiteSettings>=["site_name","header_tagline","logo_url","favicon_url","hero_image_url","announcement_enabled","announcement_text","announcement_url","whatsapp","instagram","shopee_showcase","tiktok","youtube","facebook","telegram","email","footer_title","footer_description","footer_note","seo_title","seo_description","og_image_url","products_per_page","carousel_speed"];const{error:saveError}=await supabase.from("site_settings").upsert(keys.map((key)=>({key,value:form[key]})),{onConflict:"key"});if(saveError)setError(saveError.message);else setMessage("Configurações publicadas.");setSaving(false);}
 const tabs:Array<[Tab,string,IconName]>=[["brand","Marca","image"],["content","Conteúdo geral","text"],["social","Redes e contato","link"],["seo","SEO e compartilhamento","search"]];
 const uploadCard=(field:UploadField,label:string,description:string)=><div className="settings-upload-card-v5"><div>{form[field]?<img src={form[field]} alt=""/>:<Icon name="image" size={28}/>}</div><strong>{label}</strong><small>{description}</small><label className="admin-button-v5 secondary"><Icon name="image"/>{uploading===field?"Enviando...":"Trocar imagem"}<input hidden type="file" accept="image/*" onChange={(e)=>void upload(field,e.target.files?.[0])}/></label></div>;
 return <><div className="admin-page-heading-v5"><div><span>CONFIGURAÇÕES</span><h1>Marca, conteúdo e SEO</h1><p>Dados gerais que não pertencem ao editor de blocos ou à aparência.</p></div><a href="/" target="_blank" className="admin-button-v5 secondary"><Icon name="eye"/>Abrir site</a></div>{error?<div className="admin-alert-v5 error">{error}</div>:null}{message?<div className="admin-alert-v5 success">{message}</div>:null}<form onSubmit={save} className="appearance-layout-v5"><aside className="settings-tabs-v5">{tabs.map(([key,label,icon])=><button type="button" key={key} className={tab===key?"active":""} onClick={()=>setTab(key)}><Icon name={icon}/>{label}</button>)}</aside><section className="admin-card-v5 appearance-editor-v5">
  {tab==="brand"?<><div className="admin-card-head-v5"><div><small>IDENTIDADE</small><h2>Marca do site</h2><p>Logo, ícone do navegador e nome.</p></div></div><div className="settings-upload-grid-v5">{uploadCard("logo_url","Logo principal","Usada no cabeçalho e no painel.")}{uploadCard("favicon_url","Ícone do navegador","Prefira uma imagem quadrada.")}{uploadCard("hero_image_url","Imagem de apresentação","Usada quando o bloco inicial tiver imagem.")}</div><div className="admin-form-grid-v5 settings-fields-v5"><label><span>Nome do site</span><input value={form.site_name} onChange={(e)=>update("site_name",e.target.value)} required/></label><label><span>Texto curto da marca</span><input value={form.header_tagline} onChange={(e)=>update("header_tagline",e.target.value)} placeholder="Achadinhos da Shopee"/></label><label className="full"><span>URL da logo</span><input value={form.logo_url} onChange={(e)=>update("logo_url",e.target.value)}/></label></div></>:null}
  {tab==="content"?<><div className="admin-card-head-v5"><div><small>CONTEÚDO GERAL</small><h2>Faixa do topo e comportamento</h2></div></div><div className="admin-form-grid-v5"><label className="checkbox-card-v5 full"><input type="checkbox" checked={form.announcement_enabled} onChange={(e)=>update("announcement_enabled",e.target.checked)}/><span><strong>Mostrar faixa no topo</strong><small>Use para uma mensagem curta e importante.</small></span></label><label><span>Texto da faixa</span><input value={form.announcement_text} onChange={(e)=>update("announcement_text",e.target.value)}/></label><label><span>Link da faixa</span><input value={form.announcement_url} onChange={(e)=>update("announcement_url",e.target.value)} placeholder="#produtos-dos-videos"/></label><label><span>Produtos por carregamento</span><input type="number" min="4" max="100" value={form.products_per_page} onChange={(e)=>update("products_per_page",Number(e.target.value))}/></label><label><span>Tempo do carrossel (ms)</span><input type="number" min="3000" max="15000" step="500" value={form.carousel_speed} onChange={(e)=>update("carousel_speed",Number(e.target.value))}/></label></div></>:null}
  {tab==="social"?<><div className="admin-card-head-v5"><div><small>CONTATO</small><h2>Redes sociais</h2><p>Campos vazios não aparecem no site.</p></div></div><div className="social-grid-v5">{([['instagram','Instagram','instagram'],['tiktok','TikTok','tiktok'],['shopee_showcase','Vitrine Shopee','store'],['whatsapp','WhatsApp','whatsapp'],['youtube','YouTube','youtube'],['facebook','Facebook','facebook'],['telegram','Telegram','telegram']] as const).map(([field,label,icon])=><label key={field}><span><Icon name={icon}/>{label}</span><input type="url" value={form[field]} onChange={(e)=>update(field,e.target.value)} placeholder="https://..."/></label>)}<label><span><Icon name="mail"/>E-mail</span><input type="email" value={form.email} onChange={(e)=>update("email",e.target.value)} placeholder="contato@..."/></label></div></>:null}
  {tab==="seo"?<><div className="admin-card-head-v5"><div><small>GOOGLE E REDES</small><h2>SEO geral</h2><p>Como o site aparece em pesquisas e ao compartilhar.</p></div></div><div className="admin-form-grid-v5"><label className="full"><span>Título do site</span><input value={form.seo_title} onChange={(e)=>update("seo_title",e.target.value)} maxLength={70}/><small>{form.seo_title.length}/70</small></label><label className="full"><span>Descrição</span><textarea rows={4} value={form.seo_description} onChange={(e)=>update("seo_description",e.target.value)} maxLength={180}/><small>{form.seo_description.length}/180</small></label><div className="full settings-og-row-v5">{uploadCard("og_image_url","Imagem de compartilhamento","Aparece no WhatsApp, Facebook e outras redes.")}</div><div className="seo-preview-v5 full"><small>PRÉVIA</small><h3>{form.seo_title}</h3><span>hs-achadinhos.vercel.app</span><p>{form.seo_description}</p></div></div></>:null}
  <div className="form-actions-v5 settings-sticky-save-v5"><button className="admin-button-v5" disabled={saving}><Icon name="save"/>{saving?"Salvando...":"Salvar configurações"}</button></div>
 </section></form></>;
}
